name: express-mock-api-middleware CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn test
        yarn pack
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: express-mock-api-middleware
        path: express-mock-api-middleware-*.tgz
